apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
