apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-argocd
spec:
  ai:
    enabled: true
    model: gpt-4o-mini
    backend: openai
    anonymized: true
    language: english
  noCache: true
  version: v0.4.5
  resources:
    requests: {}
    limits: {}
  # filters:
  #   - Ingress
  # sink:
  #   type: slack
  #   webhook: <webhook-url>
  # extraOptions:
  #   backstage:
  #     enabled: true
