apiVersion: v1
kind: ConfigMap
metadata:
  name: hook-config
  namespace: argocon26
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: '-1'
data:
  hook: config
