apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/argoproj/argo-cd//manifests/cluster-install/?ref=master
  - ./base

patches:
  - path: ./patch/config/argocd-cm.yaml
  - path: ./patch/config/argocd-cmd-params-cm.yaml
  - path: ./patch/config/argocd-rbac-cm.yaml

images:
  - name: quay.io/argoproj/argocd
    newTag: v3.2.0-rc4

# Update pull policy to IfNotPresent for kind cluster and private registries
configMapGenerator:
  - name: replacement-config
    options:
      disableNameSuffixHash: true
    literals:
      - imagePullPolicy=IfNotPresent

replacements:
  - source:
      kind: ConfigMap
      name: replacement-config
      fieldPath: data.imagePullPolicy
    targets:
      - select:
          group: apps
          kind: Deployment
        options:
          create: true
        fieldPaths:
          - spec.template.spec.containers.*.imagePullPolicy
      - select:
          group: apps
          kind: Deployment
          name: argocd-dex-server
        options:
          create: true
        fieldPaths:
          - spec.template.spec.initContainers.*.imagePullPolicy
      - select:
          group: apps
          kind: Deployment
          name: argocd-repo-server
        options:
          create: true
        fieldPaths:
          - spec.template.spec.initContainers.*.imagePullPolicy
      - select:
          group: apps
          kind: Deployment
          name: argocd-redis
        options:
          create: true
        fieldPaths:
          - spec.template.spec.initContainers.*.imagePullPolicy
      - select:
          group: apps
          kind: StatefulSet
        options:
          create: true
        fieldPaths:
          - spec.template.spec.containers.*.imagePullPolicy
